server:
  port: 8084

spring:
    application:
        name: subscription-service
    datasource:
        url: jdbc:postgresql://event-db:5432/eventdb
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    data:
        redis:
            host: redis
            port: 6379
    kafka:
        bootstrap-servers: kafka:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            security:
                protocol: PLAINTEXT
        consumer:
            group-id: subscription-service-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            security:
                protocol: PLAINTEXT