server:
  port: 8084

spring:
  application:
    name: subscription-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://subscription-db:5432/subscriptiondb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: "Europe/Moscow"
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      security:
        protocol: PLAINTEXT
    consumer:
      group-id: subscription-event-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      security:
        protocol: PLAINTEXT
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

outbox:
  scheduler:
    send-delay-ms: ${OUTBOX_SEND_DELAY_MS:1000}
    delete-crone: ${OUTBOX_DELETE_CRON:0 */1 * * * *}
  batch-size: ${OUTBOX_BATCH_SIZE:10}
  max-attemt: ${OUTBOX_MAX_ATTEMPT:5}
  attempt-delay-sec: ${OUTBOX_ATTEMPT_DELAY_SEC:3600}